#!/usr/bin/env node

const path = require('path');
const fs = require('fs');
const log = require('./core/log');

// Load .env from project root
const envPath = path.join(__dirname, '..', '.env');
function loadEnvFile() {
  if (fs.existsSync(envPath)) {
    for (const line of fs.readFileSync(envPath, 'utf8').split('\n')) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      const eq = trimmed.indexOf('=');
      if (eq > 0) {
        process.env[trimmed.substring(0, eq)] = trimmed.substring(eq + 1);
      }
    }
  }
}
loadEnvFile();

/**
 * Ensure WEB_TOKEN exists in .env. If not, generate one and write it.
 * Called at the start of `start` and `server` commands to solve the
 * auth chicken-and-egg problem for first-time users.
 */
function ensureWebToken() {
  if (process.env.WEB_TOKEN) return;

  // Check if .env already has an uncommented WEB_TOKEN line
  let envContent = '';
  if (fs.existsSync(envPath)) {
    envContent = fs.readFileSync(envPath, 'utf8');
    if (envContent.split('\n').some(l => !l.trim().startsWith('#') && l.includes('WEB_TOKEN='))) return;
  }

  const token = require('crypto').randomBytes(16).toString('hex');
  const newContent = envContent
    ? envContent.trimEnd() + '\nWEB_TOKEN=' + token + '\n'
    : '# Auto-generated by hive\nWEB_PORT=3001\nWEB_TOKEN=' + token + '\n';

  fs.writeFileSync(envPath, newContent);
  // Reload env so process.env picks up the new token
  loadEnvFile();

  const port = process.env.WEB_PORT || 3001;
  log.info('');
  log.info('=== First-time setup ===');
  log.info(`Open http://localhost:${port} and enter token: ${token}`);
  log.info('(Saved to .env)');
  log.info('');
}

// Load config
const configPath = path.join(__dirname, '..', 'hive.config.js');
function loadConfig() {
  if (!fs.existsSync(configPath)) {
    log.error('Missing hive.config.js -- copy from hive.config.example.js and customize.');
    process.exit(1);
  }
  return require(configPath);
}

const USAGE = `
Usage: hive <command> [options]

Commands:
  start [--daemon]   Create tmux sessions, start Claude, run dashboard
  stop               Kill all fleet sessions and the dashboard
  status             Show fleet sessions and server status
  server             Run the dashboard server only (no session management)
  init               (coming soon) Interactive setup wizard
  help               Show this help message

Options:
  --daemon           Run the dashboard in a background tmux session
  --no-sessions      Start the dashboard without creating tmux sessions

Examples:
  hive start           Start fleet + dashboard (foreground)
  hive start --daemon  Start fleet + dashboard (background)
  hive stop            Tear down everything
  hive status          Check what's running
  hive server          Dashboard only (like npm start)
`.trim();

// ── Commands ─────────────────────────────────────────────

async function cmdStart(args) {
  ensureWebToken();
  const config = loadConfig();
  const sessionManager = require('./core/session-manager');
  const isDaemon = args.includes('--daemon');
  const noSessions = args.includes('--no-sessions');
  const setupPath = path.join(__dirname, '..', '.hive-setup.json');
  const setupExists = fs.existsSync(setupPath);

  // Skip session creation if setup wizard hasn't run yet
  if (!noSessions && setupExists) {
    if (!(await sessionManager.isTmuxAvailable())) {
      log.error('tmux is not installed or not in PATH');
      process.exit(1);
    }

    // Apply global options
    log.info('Applying tmux global options...');
    await sessionManager.applyGlobalOptions(config.tmux || {});

    // Create sessions
    log.info('Creating fleet sessions...');
    const results = await sessionManager.createAllSessions(config);
    log.info(`Sessions: ${results.created.length} created, ${results.skipped.length} skipped, ${results.failed.length} failed`);

    if (results.created.length > 0) {
      log.info(`Created: ${results.created.join(', ')}`);
    }
    if (results.skipped.length > 0) {
      log.info(`Skipped (already exist): ${results.skipped.join(', ')}`);
    }
    if (results.failed.length > 0) {
      for (const f of results.failed) {
        log.error(`  Session ${f.num}: ${f.error}`);
      }
    }

    // Start Claude in newly created sessions
    const claudePane = config.sessions?.claudePane || 1;
    const prefix = config.sessions?.namePrefix || '';
    for (const num of results.created) {
      try {
        await sessionManager.startClaude(`${prefix}${num}`, claudePane);
      } catch (err) {
        log.error(`Failed to start Claude in session ${num}: ${err.message}`);
      }
    }
  } else if (!noSessions && !setupExists) {
    log.info('No .hive-setup.json found — skipping session creation (complete setup wizard in browser)');
  }

  // Start dashboard
  if (isDaemon) {
    const tmux = require('./core/tmux');
    const hiveDir = path.join(__dirname, '..');
    const serverCmd = `node ${path.join(__dirname, 'index.js')} 2>&1 | tee -a ${path.join(hiveDir, 'hive.log')}`;
    await tmux.exec(`tmux new-session -d -s hive-server -c "${hiveDir}" "${serverCmd}"`);
    log.info('Dashboard started in background (tmux session: hive-server)');
    log.info('  Attach: tmux attach -t hive-server');
    log.info(`  Logs:   tail -f ${path.join(hiveDir, 'hive.log')}`);
  } else {
    log.info('Starting dashboard server (foreground)...');
    require('./index');
  }
}

async function cmdStop() {
  const config = loadConfig();
  const tmux = require('./core/tmux');
  const sessionManager = require('./core/session-manager');

  // Kill hive-server session if it exists
  if (await tmux.hasSession('hive-server')) {
    await tmux.killSession('hive-server');
    log.info('Killed hive-server session');
  }

  // Destroy fleet sessions
  const results = await sessionManager.destroyAllSessions(config);
  if (results.killed.length > 0) {
    log.info(`Killed ${results.killed.length} session(s): ${results.killed.join(', ')}`);
  } else {
    log.info('No fleet sessions found');
  }
  if (results.failed.length > 0) {
    for (const f of results.failed) {
      log.error(`  Failed to kill "${f.name}": ${f.error}`);
    }
  }
}

async function cmdStatus() {
  const config = loadConfig();
  const tmux = require('./core/tmux');
  const prefix = config.sessions?.namePrefix || '';
  const pattern = prefix
    ? new RegExp('^' + prefix.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '\\d+')
    : (config.sessions?.pattern || /^\d+/);

  const sessions = await tmux.listSessions();
  const fleetSessions = sessions.filter(s => pattern.test(s.name));
  const hasServer = await tmux.hasSession('hive-server');

  console.log(`Fleet sessions: ${fleetSessions.length}`);
  if (fleetSessions.length > 0) {
    for (const s of fleetSessions) {
      console.log(`  ${s.name}`);
    }
  }
  console.log(`Dashboard: ${hasServer ? 'running (hive-server)' : 'not running'}`);
}

function cmdServer() {
  ensureWebToken();
  log.info('Starting dashboard server...');
  require('./index');
}

function cmdInit() {
  console.log('hive init -- coming soon');
  console.log('For now, edit hive.config.js manually.');
}

function cmdHelp() {
  console.log(USAGE);
}

// ── Router ───────────────────────────────────────────────

const [command, ...args] = process.argv.slice(2);

switch (command) {
  case 'start':
    cmdStart(args).catch(err => {
      log.error(`start failed: ${err.message}`);
      process.exit(1);
    });
    break;
  case 'stop':
    cmdStop().catch(err => {
      log.error(`stop failed: ${err.message}`);
      process.exit(1);
    });
    break;
  case 'status':
    cmdStatus().catch(err => {
      log.error(`status failed: ${err.message}`);
      process.exit(1);
    });
    break;
  case 'server':
    cmdServer();
    break;
  case 'init':
    cmdInit();
    break;
  case 'help':
  case '--help':
  case '-h':
    cmdHelp();
    break;
  default:
    if (command) {
      log.error(`Unknown command: ${command}`);
    }
    cmdHelp();
    if (command) process.exit(1);
    break;
}
